name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker and Docker Compose
        uses: docker-practice/actions-setup-docker@v1

      - name: Build and run containers
        run: docker-compose up -d --build


      - name: Wait for database to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          max_retries=10
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
            if docker-compose exec db pg_isready -U user -h localhost; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "PostgreSQL not ready yet, retrying in 5 seconds..."
            sleep 5
            retry_count=$((retry_count + 1))
          done
          if [ $retry_count -eq $max_retries ]; then
            echo "Failed to connect to PostgreSQL after $max_retries attempts."
            exit 1
          fi

      - name: Run Ruff checks
        run: docker-compose exec app ruff check .

      - name: Apply migrations
        run: docker-compose exec app python manage.py migrate


      - name: Run Django tests
        run: docker-compose exec app python manage.py test

      - name: Stop containers
        if: always()
        run: docker-compose down